version: 2
jobs:
  build:
    working_directory: ~/fe-app
    docker:
      - image: circleci/node:15-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --legacy-peer-deps
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install tools & lint & test
          command: |
            sudo npm install -g firebase-tools;
            sudo npm install -g @angular/cli > /dev/null;
      - run:
          name: Deploy to Firebase
          command: |
            ng build --aot --prod --outputHashing=all --base-href='https://a12test.web.app/'
            firebase deploy --project a12test --token=1//0emONBV5mr1IdCgYIARAAGA4SNwF-L9IrlDALYF7M9xUFh3JFyFYCLJ5jhCfesq2iakp8p88m1CpY2apexym_OK_mFFxwXJhBR8k
workflows:
  version: 2
  workflow:
    jobs:
      - build
